### ISSUE TITLE
Arm images can't run web based tests in chrome

### ISSUE THREAD

**Issue by nhal** [butomo1989/docker-android#63]
**Steps:**
* Spin up an arm image with google chrome enabled by default (docker-android-arm-7.1.1/7.0/6.0). 
* Use MOBILE_WEB_TEST=True.
* Attempt to run a chrome test on the device.

**Output:** 
The image starts fine but is unable to get chrome going. This same behavior is not shown in x86 images.
![arm_emulator_stacktrace](https://user-images.githubusercontent.com/16785491/35855558-e472fc9c-0b33-11e8-88cc-e1228423b03b.png)

The configuration used is as follows: 
```yml
android-emulator:
    image: butomo1989/docker-android-arm-7.1.1
    ports:
      - 6080:6080
      - 4723:4723
    privileged: true
    environment:
      - DEVICE=Nexus 5
      - CONNECT_TO_GRID=True
      - APPIUM=true
      - APPIUM_HOST=android-emulator
      - APPIUM_PORT=4723
      - SELENIUM_HOST=selenium-hub
      - SELENIUM_PORT=4444
      - MOBILE_WEB_TEST=True
```

And the driver capabilities used in the testing code:
```java
capabilities.setCapability(CapabilityType.BROWSER_NAME, MobileBrowserType.CHROME);
capabilities.setCapability("platformName", "Android");
capabilities.setCapability("deviceName", "Nexus 5");
```

**Expected results:**
Be able to run chrome-based tests in any arm image.
